INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Jessica', 'Hartman', 'patrick80@moore-zimmerman.biz');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Cindy', 'Kim', 'hilljessica@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Valerie', 'Manning', 'gilbertmatthew@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Paul', 'Smith', 'loweryderek@drake.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Jessica', 'Duffy', 'cindy28@jones.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Alexis', 'Evans', 'kimberly57@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Dakota', 'Morrison', 'zlittle@miller.org');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Aaron', 'Wilson', 'rodriguezchristopher@chapman.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Sarah', 'Mcbride', 'heathercobb@smith-johnson.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Melissa', 'Paul', 'wcombs@flynn.org');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Donald', 'Richards', 'zsimmons@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('James', 'Sherman', 'milleralyssa@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Edward', 'Roberts', 'james28@harvey.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Lisa', 'Garcia', 'jacob14@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kathleen', 'Chang', 'tdiaz@hampton.info');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Peggy', 'Bauer', 'pattersontammy@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kayla', 'Eaton', 'xscott@meyers.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Bill', 'Davis', 'robinsonjulia@ball.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Susan', 'Young', 'olsonjohn@daniel.info');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Aaron', 'Sullivan', 'tyang@brown.biz');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Cristina', 'Parker', 'yjones@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('William', 'Weaver', 'jonesrobert@ortiz-reyes.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Andrea', 'Conner', 'dbright@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Dennis', 'Wagner', 'mwilson@graham-day.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Nathan', 'Duncan', 'ucooper@moyer-brown.org');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kimberly', 'Miranda', 'kenneth63@figueroa.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Samantha', 'Owens', 'brandon96@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Emily', 'Mcdonald', 'lsantos@davis.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Robert', 'Walsh', 'pkennedy@guzman.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('William', 'Carter', 'stacy36@scott.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Tyler', 'Webster', 'johnflores@hotmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Matthew', 'Peterson', 'lauren20@simpson.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Howard', 'Copeland', 'kimberlyjones@barnes.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Randy', 'Murphy', 'bergertina@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Nicholas', 'Knight', 'patriciajones@gill-beard.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('David', 'Wallace', 'wendyfletcher@rogers.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Anna', 'Green', 'parsonsdouglas@mack.biz');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Shelley', 'Thomas', 'patriciaadams@sparks-poole.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Robert', 'Edwards', 'edwardgallegos@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Kent', 'Hines', 'seanortiz@donaldson-moore.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Christopher', 'Lee', 'mcculloughjoseph@bishop.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Jennifer', 'Mejia', 'lisaroth@hoover.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Nancy', 'Davis', 'gilbertlopez@gmail.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Cathy', 'Kim', 'laura20@herrera-vaughan.net');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Chad', 'Hanson', 'ianobrien@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Ryan', 'Gibson', 'joshuamartin@hanna.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Tracy', 'Payne', 'dhoward@dennis.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Joseph', 'Webb', 'xjohnson@yahoo.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Margaret', 'Johnson', 'tayloramanda@gomez-moore.com');
INSERT INTO ALUMNOS (nombre, apellido, correo) VALUES ('Wendy', 'Atkinson', 'brenda39@yahoo.com');
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (1, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (1, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (38, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (31, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (19, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (13, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (14, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (48, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (7, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (11, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (16, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (5, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (36, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (32, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (32, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (5, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (31, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (41, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (4, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (9, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (4, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (36, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (1, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (5, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (9, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (7, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (49, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (33, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (48, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (24, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (24, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (22, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (32, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (7, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (8, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (16, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (19, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (31, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (28, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (38, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (38, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (32, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (2, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (32, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (42, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (50, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (18, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (14, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (5, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (38, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (20, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (19, 5);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (29, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (4, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (4, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (37, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (35, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (17, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (32, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (47, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (13, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (15, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (8, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (50, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (17, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (42, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (38, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (34, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (22, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (23, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (50, 2);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (16, 3);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (34, 4);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (35, 1);
INSERT INTO ALUMNOS_CURSOS (ID_ALUMNO, ID_CURSO) VALUES (30, 2);
